on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Run Code Quality Tests
    timeout-minutes: 10
    runs-on: macos-12
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          channel: stable
          flutter-version: "3.3.8"

      - name: Run golden tests
        working-directory: ./libs/spend_lib
        run: flutter test
